# Generated by Django 5.1.7 on 2025-04-09 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_review_created_at_alter_review_employer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='student',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='city',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(choices=[('RUB', '₽'), ('USD', '$'), ('EUR', '€')], default='RUB', max_length=10),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='deadline',
            field=models.DateField(default='2025-12-31'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_max',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='salary_min',
            field=models.PositiveIntegerField(default='0'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='employer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
