# Generated by Django 5.1.7 on 2025-04-09 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('student', 'Студент'), ('employer', 'Работодатель')], default='student', max_length=10),
        ),
    ]
