# Generated by Django 5.1.7 on 2025-04-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='is_read',
            new_name='read',
        ),
    ]
