# Generated by Django 5.1.7 on 2025-04-09 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationView',
        ),
    ]
